import { useMemo } from "react";
import { ConversionRecord } from "@/lib/types";
import { useWorkbenchViewProps } from "@/hooks/useWorkbenchViewProps";
import type { WorkbenchDomainModel } from "@/hooks/useWorkbenchContracts";

export function useWorkbenchPresentationProps(domain: WorkbenchDomainModel) {
  const overlaysBase = useMemo(
    () => ({
      showDiff: domain.diff.showDiff,
      currentDiff: domain.diff.currentDiff,
      onCloseDiff: () => domain.diff.setShowDiff(false),
      showHistory: domain.showHistory,
      history: domain.history,
      onCloseHistory: () => domain.setShowHistory(false),
      showValidationConfigurator: domain.showValidationConfigurator,
      onCloseValidationConfigurator: () =>
        domain.setShowValidationConfigurator(false),
      showTemplateEditor: domain.showTemplateEditor,
      onCloseTemplateEditor: () => domain.setShowTemplateEditor(false),
      currentSampleData: domain.pasteText || undefined,
      showCommandPalette: domain.showCommandPalette,
      onShowCommandPaletteChange: domain.setShowCommandPalette,
      onTogglePreview: domain.togglePreview,
      templates: domain.templates,
      currentTemplate: domain.format,
      onSelectTemplate: domain.setFormat,
      hasOutput: Boolean(domain.mdflowOutput),
      showFeedback: domain.showFeedback,
      inputSource: domain.inputSource,
    }),
    [domain]
  );

  const sourcePanelBase = useMemo(
    () => ({
      mode: domain.mode,
      pasteText: domain.pasteText,
      onPasteTextChange: domain.setPasteText,
      file: domain.file,
      onFileChange: domain.setFile,
      sheets: domain.sheets,
      selectedSheet: domain.selectedSheet,
      onSelectSheet: domain.setSelectedSheet,
      format: domain.format,
      onFormatChange: domain.setFormat,
      preview: domain.preview,
      showPreview: domain.showPreview,
      onTogglePreview: domain.togglePreview,
      previewLoading: domain.previewLoading,
      columnOverrides: domain.columnOverrides,
      onColumnOverride: domain.review.handleColumnOverride,
      openaiKey: domain.openaiKey,
      setOpenaiKey: domain.setOpenaiKey,
      clearOpenaiKey: domain.clearOpenaiKey,
      showApiKeyInput: domain.showApiKeyInput,
      onToggleApiKeyInput: domain.toggleApiKeyInput,
      apiKeyDraft: domain.apiKeyDraft,
      onApiKeyDraftChange: domain.setApiKeyDraft,
      error: domain.error,
      mappedAppError: domain.mappedAppError,
      lastFailedAction: domain.lastFailedAction,
      reviewRequiredColumns: domain.review.reviewRequiredColumns,
      reviewedColumns: domain.review.reviewedColumns,
      reviewRemainingCount: domain.review.reviewRemainingCount,
      canConfirmReview: domain.canConfirmReviewGate,
      onCompleteReview: domain.review.completeReview,
      requiresReviewApproval: domain.review.requiresReviewApproval,
      reviewApproved: domain.review.reviewApproved,
      googleSheetInput: domain.googleSheetInputProps,
      isInputGsheetUrl: domain.isInputGsheetUrl,
      fileHandling: domain.fileHandlingProps,
      loading: domain.loading,
    }),
    [
      domain.mode,
      domain.pasteText,
      domain.setPasteText,
      domain.file,
      domain.setFile,
      domain.sheets,
      domain.selectedSheet,
      domain.setSelectedSheet,
      domain.format,
      domain.setFormat,
      domain.preview,
      domain.showPreview,
      domain.togglePreview,
      domain.previewLoading,
      domain.columnOverrides,
      domain.review.handleColumnOverride,
      domain.openaiKey,
      domain.setOpenaiKey,
      domain.clearOpenaiKey,
      domain.showApiKeyInput,
      domain.toggleApiKeyInput,
      domain.apiKeyDraft,
      domain.setApiKeyDraft,
      domain.error,
      domain.mappedAppError,
      domain.lastFailedAction,
      domain.review.reviewRequiredColumns,
      domain.review.reviewedColumns,
      domain.review.reviewRemainingCount,
      domain.canConfirmReviewGate,
      domain.review.completeReview,
      domain.review.requiresReviewApproval,
      domain.review.reviewApproved,
      domain.googleSheetInputProps,
      domain.isInputGsheetUrl,
      domain.fileHandlingProps,
      domain.loading,
    ]
  );

  const outputPanelBase = useMemo(
    () => ({
      mdflowOutput: domain.mdflowOutput,
      loading: domain.loading,
      meta: domain.meta,
      warnings: domain.warnings,
      aiSuggestions: domain.aiSuggestions,
      aiSuggestionsLoading: domain.aiSuggestionsLoading,
      aiSuggestionsError: domain.aiSuggestionsError,
      aiConfigured: domain.aiConfigured,
      requiresReviewApproval: domain.review.requiresReviewApproval,
      reviewApproved: domain.review.reviewApproved,
      reviewGateReason: domain.review.reviewGateReason,
      format: domain.format,
      copied: domain.output.copied,
      onCopy: domain.output.handleCopy,
      onDownload: domain.output.handleDownload,
      snapshotA: domain.diff.snapshotA,
      snapshotB: domain.diff.snapshotB,
      compareLoading: domain.diff.compareLoading,
      historyCount: domain.history.length,
    }),
    [
      domain.mdflowOutput,
      domain.loading,
      domain.meta,
      domain.warnings,
      domain.aiSuggestions,
      domain.aiSuggestionsLoading,
      domain.aiSuggestionsError,
      domain.aiConfigured,
      domain.review.requiresReviewApproval,
      domain.review.reviewApproved,
      domain.review.reviewGateReason,
      domain.format,
      domain.output.copied,
      domain.output.handleCopy,
      domain.output.handleDownload,
      domain.diff.snapshotA,
      domain.diff.snapshotB,
      domain.diff.compareLoading,
      domain.history.length,
    ]
  );

  return useWorkbenchViewProps({
    sourcePanelBase,
    outputPanelBase,
    overlaysBase,
    setMode: domain.setMode,
    setFile: domain.setFile,
    reviewRequiredColumns: domain.review.reviewRequiredColumns,
    setReviewedColumns: domain.review.setReviewedColumns,
    onRetryFailedAction: domain.handleRetryFailedAction,
    onConvert: domain.handleConvert,
    onOpenTemplateEditor: domain.openTemplateEditor,
    onOpenValidation: domain.openValidationConfigurator,
    onRetryAISuggestions: domain.retryAISuggestions,
    onSaveSnapshot: domain.saveSnapshot,
    onCompareSnapshots: domain.compareSnapshots,
    onClearSnapshots: domain.clearSnapshots,
    onShowHistory: domain.openHistory,
    onSelectHistory: (record: ConversionRecord) => {
      domain.setResult(record.output, [], record.meta!);
      domain.setShowHistory(false);
    },
    onDismissFeedback: () => domain.setShowFeedback(false),
    onCopyCommand: domain.handleCommandPaletteCopy,
    onExportCommand: domain.handleCommandPaletteExport,
    format: domain.format,
  });
}
